### PR TITLE
remove checking duckdb_appender_create in extconf.rb

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#302

### CODE REVIEW

**Comment by suketa** [comment]
@RishiKumarRay 

Could you change ext/duckdb/extconf.rb ?
We don't need to check `duckdb_appender_create` function any more.

**Comment by RishiKumarRay** [comment]
@suketa change to what , didn't got it , i have removed all occurences can you give more context like what is remaining ? please

**Comment by RishiKumarRay** [comment]
oh i think i got it let me try @suketa

**Review by suketa — APPROVED** [review]
Thank you

**Comment by suketa** [comment]
@RishiKumarRay 
update ext/duckdb/appender.h to fix build error.

**Review by suketa — COMMENTED** [review]
@RishiKumarRay 
update appender.h to fix build error

**Review by suketa — CHANGES_REQUESTED** [review]
update appender.h to fix build error.

**Comment by Ashvith** [comment]
@suketa if this PR is dead, then you can assign this task to me.

**Comment by suketa** [comment]
@Ashvith 
Thank you, I assigned to you.

**Comment by Ashvith** [comment]
I am not sure on how I can push my changes onto someone else's PR. Will give a try, and if that does not work, I'll open a new PR.

**Comment by Ashvith** [comment]
@suketa you can close this branch. I tried [some](https://stackoverflow.com/questions/22237609/adding-to-someone-else-s-pull-request-on-a-github-project-that-i-do-not-own) tutorials, but it looks like I would need the permission of the person who made the PR (I believe?). Since they're not responding, and I am not an expert in advanced Git, I'll open a new PR.

**Comment by suketa** [comment]
@Ashvith OK, I close this PR

**Pull request closed without merging**
